[build]
target = "armv7a-none-eabi"

[target.armv7a-none-eabi]
runner = [
    "sh",
    "-c",
    '''
    kernel="$1"
    gdb_args=""
    display="${QEMU_DISPLAY:-cocoa}"

    if [ "${QEMU_GDB:-0}" = "1" ]; then
        gdb_args="-s -S"
    fi

    export QEMU_AUDIO_DRV=none

    exec qemu-system-arm \
        -M versatilepb \
        -cpu cortex-a8 \
        -m 128M \
        -serial mon:stdio \
        -display "$display" \
        $gdb_args \
        -kernel "$kernel"
    ''',
    "--",
]

rustflags = [
    "-C",
    "linker=rust-lld",
    "-C",
    "link-arg=-Tlinker.ld",
    "--cfg",
    "target_board=\"versatilepb\"",
]

[target.aarch64-unknown-none]
runner = [
    "sh",
    "-c",
    '''
kernel="$1"
gdb_args=""

case "$kernel" in
    */debug/*) gdb_args="-s -S" ;;
esac

exec qemu-system-aarch64 \
    -M raspi4b \
    -cpu cortex-a72 \
    -serial mon:stdio \
    -display none \
    $gdb_args \
    -kernel "$kernel"
''',
    "--",
]

rustflags = [
    "-C",
    "linker=rust-lld",
    "-C",
    "link-arg=-Tlinker.ld",
    "--cfg",
    "target_board=\"raspi4b\"",
]
